name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Clean up pulled files and output directory
        run: |
          rm -rf $OUTPUT_DIR/*
      - name: Run doit (thus invoking PyDoit according to the dodo.py file)
        run: |
          doit ignore pull_options_data
          doit
      - uses: education/autograding@v1